#!/bin/sh -e

. /etc/lsb-release
while true; do
	case "$1" in
		--release)
			DISTRIB_CODENAME="$2"
			shift 2
			;;
		*)
			break
			;;
	esac
done
PAGE=`echo "$@" | awk '{print $NF}'`
MAN_ARGS=`echo "$@" | sed "s/\$PAGE$//"`

# Mirror support of man's languages
if [ ! -z "$LANG" ]; then
	LOCALE="$LANG"
fi
if [ ! -z "$LC_MESSAGES" ]; then
	LOCALE="$LC_MESSAGES"
fi
if echo $LOCALE | grep -q "^en"; then
	LOCALE=""
fi

URL="http://ubuntu.dustinkirkland.com/manpages.gz/"

mandir=`mktemp -d dman.XXXXXX`
trap "rm -rf $mandir" EXIT HUP INT QUIT TERM
for i in `seq 1 9`; do
	man="$mandir/$i"
	if wget -O $man $URL/$DISTRIB_CODENAME/$LOCALE/man$i/$PAGE.$i.gz 2>/dev/null; then
		man $MAN_ARGS -l $man || true
	fi
	rm -f $man
done
